import test from 'node:test'; import assert from 'node:assert/strict';
import { createGitHubCanonicalExecutionBridge } from '../src/githubDevelopment/githubCanonicalExecutionBridge.js';
import { createGitHubDevelopmentOrchestrator, createInMemoryGitHubDevelopmentTaskStore } from '../src/githubDevelopment/githubDevelopmentOrchestrator.js';
const HEAD='a'.repeat(40), repository={owner:'korzh260609-beep',name:'garya-bot',fullName:'korzh260609-beep/garya-bot'};
function input(transport='telegram'){return{text:'Implement GDE3',identityContext:{globalUserId:'usr-owner'},scopeContext:{projectScope:'sg2.1'},traceContext:{traceId:'t',requestId:'r-gde3'},metadata:{transport}}}
function model(){return{resolutionStatus:'resolved',action:{name:'github.development.execute'},parameters:{instruction:'Implement GDE3'},provenance:{resolver:'sg-semantic-request-resolver-v1'}}}
function target(){return{repository,branch:'dev/sg2.1-semantic',baselineHead:HEAD,connectionId:'github-development',completionCondition:{kind:'exact-head-ci-green',targetWorkflow:'SG 2.1 CI',maxAttempts:3,evidenceRequirements:['tests']},evidence:{immutableRevisionVerified:true}}}
function change(){return{filesToRead:['src/a.js'],filesToCreate:['src/new.js'],filesToModify:['src/a.js'],filesToDelete:[],tests:['tests/a.test.js'],docs:['README.md'],migrations:[],expectedPostConditions:['tests pass']}}
function harness(revision=HEAD){const executions=[];const orchestrator=createGitHubDevelopmentOrchestrator({taskStore:createInMemoryGitHubDevelopmentTaskStore(),taskExecutor:{async resume(x){executions.push(x);return{nextAction:'build-change-set'}}}});const bridge=createGitHubCanonicalExecutionBridge({orchestrator,repositoryReadService:{async readSnapshot(){return{revision}}},developmentPlanner:{async plan(){return change()}}});return{bridge,executions}}
test('GDE3 canonical execute reaches the existing GH3 orchestrator with one bounded task/change set',async()=>{const {bridge,executions}=harness();const result=await bridge.execute({canonicalInput:input(),canonicalModel:model(),resolvedTarget:target(),capabilityAssessment:{available:true,capabilities:['github.repository.read','github.code.search','github.contents.write','github.commit.create']}});assert.equal(result.executionOwner,'GitHubDevelopmentOrchestrator');assert.equal(result.task.status,'running');assert.deepEqual(result.task.developmentPlan,change());assert.equal(executions.length,1);assert.equal(executions[0].task.baseline.sha,HEAD)});
test('GDE3 transport equivalence preserves deterministic task identity and scope',async()=>{const a=await harness().bridge.execute({canonicalInput:input('telegram'),canonicalModel:model(),resolvedTarget:target(),capabilityAssessment:{available:true,capabilities:['github.repository.read']}});const b=await harness().bridge.execute({canonicalInput:input('web-api'),canonicalModel:model(),resolvedTarget:target(),capabilityAssessment:{available:true,capabilities:['github.repository.read']}});assert.equal(a.task.taskId,b.task.taskId);assert.equal(JSON.stringify(a).includes('telegram'),false)});
test('GDE3 rejects stale HEAD before orchestrator mutation',async()=>{const {bridge,executions}=harness('b'.repeat(40));await assert.rejects(()=>bridge.execute({canonicalInput:input(),canonicalModel:model(),resolvedTarget:target(),capabilityAssessment:{available:true,capabilities:['github.repository.read']}}),e=>e.code==='gde3-stale-head');assert.equal(executions.length,0)});
test('GDE3 rejects unavailable capability, duplicate paths and unsupported canonical actions',async()=>{const {bridge}=harness();await assert.rejects(()=>bridge.execute({canonicalInput:input(),canonicalModel:model(),resolvedTarget:target(),capabilityAssessment:{available:false}}),e=>e.code==='gde3-capability-unavailable');const bad=createGitHubCanonicalExecutionBridge({orchestrator:{handle:async()=>{}},repositoryReadService:{readSnapshot:async()=>({revision:HEAD})},developmentPlanner:{plan:async()=>({...change(),filesToCreate:['src/a.js']})}});await assert.rejects(()=>bad.execute({canonicalInput:input(),canonicalModel:model(),resolvedTarget:target(),capabilityAssessment:{available:true,capabilities:[]}}),e=>e.code==='gde3-change-set-conflict');await assert.rejects(()=>bridge.execute({canonicalInput:input(),canonicalModel:{...model(),action:{name:'github.file.read'}},resolvedTarget:target(),capabilityAssessment:{available:true}}),e=>e.code==='gde3-canonical-action-unsupported')});
test('GDE3 retry reuses the same durable task and does not create duplicate execution state',async()=>{const h=harness();const args={canonicalInput:input(),canonicalModel:model(),resolvedTarget:target(),capabilityAssessment:{available:true,capabilities:['github.repository.read']}};const first=await h.bridge.execute(args);const second=await h.bridge.execute(args);assert.equal(first.task.taskId,second.task.taskId);assert.equal(second.reused,true);assert.equal(h.executions.length,2)});
