import test from 'node:test';import assert from 'node:assert/strict';
import {createGitHubPlatformOperationsService}from'../src/githubDevelopment/githubPlatformOperationsService.js';
import {CANONICAL_GITHUB_ACTIONS}from'../src/contracts/semantic.js';
import {CANONICAL_GITHUB_ACTION_CAPABILITY_BINDINGS}from'../src/githubDevelopment/githubCapabilityBindingService.js';
const A='a'.repeat(40),B='b'.repeat(40),repo={owner:'acme',name:'project'},actor={globalUserId:'u1'};
function fixture(overrides={}){const calls=[],audits=[];const dependencies={repositoryReadService:{async readSnapshot(x){calls.push(['read',x]);return{revision:A}}},discoveryService:{async search(x){calls.push(['search',x]);return{results:[],observedAt:'now'}}},atomicCommitService:{async ensureBranch(x){calls.push(['branch',x]);return{headSha:A,reused:true}},async applyAtomicCommit(x){calls.push(['commit',x]);return{commitSha:B,changedPaths:['src/a.js']}}},collaborationService:{async upsertPullRequest(x){calls.push(['pr',x]);return{pullNumber:7}},async readReviewThreads(x){calls.push(['reviews',x]);return{comments:[]}},async replyToReview(x){calls.push(['reply',x]);return{commentId:8}},async upsertIssue(x){calls.push(['issue',x]);return{issueNumber:9}},async createTagAndRelease(x){calls.push(['release',x]);return{releaseId:10}}},ciService:{async inspectExactHead(x){calls.push(['ci',x]);return{headSha:A,exactHeadVerified:true,runId:11}},async rerunFailed(x){calls.push(['rerun',x]);return{headSha:A,runId:11,reused:true}}},developmentBridge:{async execute(x){calls.push(['development',x]);return{task:{taskId:'t1'},status:'running'}}},taskStore:{async get(){return{taskId:'t1',globalUserId:'u1',projectId:'p1',repository:repo,targetRef:{name:'dev/work'},baseline:{sha:A},intent:'next stage',checkpoint:{live:{headSha:A}}}}},securityControlPlane:{async authorize(x){calls.push(['authorize',x]);return{allowed:true,gate:'allow'}}},auditSink:{async record(x){audits.push(x)}},clock:()=>new Date('2026-08-22T10:00:00Z'),...overrides};return{service:createGitHubPlatformOperationsService(dependencies),calls,audits}}
function input(action,extra={}){return{canonicalAction:action,capability:CANONICAL_GITHUB_ACTION_CAPABILITY_BINDINGS[action]?.[0]??'github.repository.read',actor,projectScope:'p1',repository:repo,branch:'dev/work',expectedHeadSha:A,repositoryResourceId:'github:repo:acme/project',connectionId:'c1',credentialId:'cred',traceContext:{traceId:'tr1',requestId:'rq1'},actionRequest:{},...extra}}

test('GDE6 canonical surface is fully bound to the existing capability system',()=>{for(const action of CANONICAL_GITHUB_ACTIONS)assert.ok(CANONICAL_GITHUB_ACTION_CAPABILITY_BINDINGS[action],action)});
test('repository and branch inspection reuse the existing reader and retain bounded audit',async()=>{const f=fixture();const result=await f.service.execute(input('github.branch.inspect'));assert.equal(f.calls.some(x=>x[0]==='read'),true);assert.equal(result.audit.canonicalAction,'github.branch.inspect');assert.equal(result.audit.oldHead,A);assert.equal(result.audit.postCondition,null);assert.equal(f.audits.length,1)});
test('public and authorized private discovery reuse one discovery service',async()=>{const f=fixture();await f.service.execute(input('github.discovery.public',{operation:{kind:'repository',query:'sg'}}));await f.service.execute(input('github.discovery.private',{operation:{kind:'code',query:'LA1'}}));const searches=f.calls.filter(x=>x[0]==='search');assert.equal(searches[0][1].visibility,'public');assert.equal(searches[1][1].visibility,'authorized-private')});
test('PR issue review workflow branch commit and release actions dispatch to existing GH3 services',async()=>{for(const [action,expected,operation]of[['github.pr.create','pr',{}],['github.issue.close','issue',{state:'closed'}],['github.review.respond','reply',{}],['github.workflow.rerun','rerun',{}],['github.branch.create','branch',{baselineSha:A}],['github.commit.create','commit',{}],['github.release.create','release',{separateApproval:true}]]){const f=fixture();await f.service.execute(input(action,{operation}));assert.equal(f.calls.some(x=>x[0]===expected),true,action);assert.equal(f.calls[0][0],'authorize')}});
test('natural-language follow-up continuity is restored only from scoped durable task state',async()=>{const f=fixture();const result=await f.service.execute(input('github.development.continue',{context:{taskId:'t1'},capabilityAssessment:{available:true,capabilities:['github.repository.read']}}));assert.equal(result.continuityTaskId,'t1');assert.equal(f.calls.some(x=>x[0]==='development'),true);const denied=fixture({taskStore:{async get(){return{taskId:'t1',globalUserId:'other',projectId:'p1',repository:repo}}}});await assert.rejects(()=>denied.service.execute(input('github.development.continue',{context:{taskId:'t1'}})),e=>e.code==='gde6-context-scope-denied')});
test('main switch missing exact HEAD and unknown actions fail closed before provider mutation',async()=>{const f=fixture();await assert.rejects(()=>f.service.execute(input('github.branch.create',{branch:'main'})),e=>e.code==='gde6-protected-branch-denied');await assert.rejects(()=>f.service.execute(input('github.branch.create',{expectedHeadSha:'short'})),e=>e.code==='gde6-exact-head-required');await assert.rejects(()=>f.service.execute(input('github.unknown')),/unsupported|capability/)});
test('authority is checked for every operation and denial emits no audit or provider call',async()=>{const f=fixture({securityControlPlane:{async authorize(){const e=new Error('denied');e.code='gh3-security-acs-denied';throw e}}});await assert.rejects(()=>f.service.execute(input('github.issue.create')),e=>e.code==='gh3-security-acs-denied');assert.equal(f.audits.length,0);assert.equal(f.calls.length,0)});
test('audit covers actor operation identity trace idempotency security and exact-head post-condition',async()=>{const f=fixture();const result=await f.service.execute(input('github.ci.verify'));assert.deepEqual(result.audit.actor,actor);assert.equal(result.audit.repository,'acme/project');assert.equal(result.audit.identity.workflowRun,11);assert.equal(result.audit.traceId,'tr1');assert.match(result.audit.idempotencyKey,/^gde6-/);assert.equal(result.audit.postCondition,'exact-head-verified');assert.equal(result.audit.timestamp,'2026-08-22T10:00:00.000Z')});
test('unverified mutation that silently retains HEAD is rejected and never claimed successful',async()=>{const f=fixture({collaborationService:{async upsertIssue(){return{headSha:A}}}});await assert.rejects(()=>f.service.execute(input('github.issue.create')),e=>e.code==='gde6-post-condition-unverified');assert.equal(f.audits.length,0)});
