import test from 'node:test';
import assert from 'node:assert/strict';
import { createGitHubSecurityControlPlane } from '../src/githubDevelopment/githubSecurityControlPlane.js';

function request(overrides = {}) { return { capability: 'github.contents.write', actor: { globalUserId: 'usr-monarch' }, projectScope: 'sg2.1', repositoryResourceId: 'github:repo:garya-bot', branch: 'dev/sg2.1-semantic', paths: ['src/example.js'], credentialId: 'cred-github', connectionId: 'github-app', actionRequest: { traceContext: { traceId: 'trace-gh311', requestId: 'request-gh311' } }, ...overrides }; }
function harness(overrides = {}) { const calls = []; const definitions = { 'github.repository.read': { name: 'github.repository.read', riskTier: 1 }, 'github.contents.write': { name: 'github.contents.write', riskTier: 2 }, 'github.release.write': { name: 'github.release.write', riskTier: 3 }, 'github.repository.admin': { name: 'github.repository.admin', riskTier: 4 } }; const service = createGitHubSecurityControlPlane({ capabilityRegistry: { get: (name) => definitions[name] ?? null }, accessControl: { async assertAllowed(input) { calls.push(['acs', input]); return { allowed: true }; } }, resourceAuthority: { async checkAuthority(input) { calls.push(['authority', input]); return { allowed: true, evidence: { authorityId: 'auth-1' }, resourceId: input.resourceId, requiredRelation: input.relation }; } }, actionGate: { evaluate(input) { calls.push(['gate', input]); return { outcome: 'allow', authorized: true }; } }, credentialManager: { async useCredential(input) { calls.push(['credential', { ...input, operation: 'callback' }]); return input.operation('installation-secret'); } }, ownerSecurity: { async evaluate(input) { calls.push(['owner', input]); return { allowed: true }; } }, rateLimiter: { async consume(input) { calls.push(['rate', input]); return { allowed: true }; } }, emergencyMode: () => 'normal', audit: async (event) => { calls.push(['audit', event]); }, clock: () => new Date('2026-08-20T12:00:00.000Z'), ...overrides }); return { service, calls }; }

test('GH3.11: mutation composes rate limit, ACS, Resource Authority, Action Gate, credential and audit', async () => { const { service, calls } = harness(); const result = await service.execute(request(), async (secret) => ({ status: 'written', usedInsideCallback: secret === 'installation-secret' })); assert.equal(result.result.usedInsideCallback, true); assert.deepEqual(calls.map(([name]) => name), ['rate','acs','authority','gate','audit','credential','audit']); assert.equal(calls.find(([name]) => name === 'authority')[1].relation, 'can_modify'); });
test('GH3.11: read-only emergency mode permits reads and denies all writes before authorization', async () => { const writes = harness({ emergencyMode: () => 'read-only' }); await assert.rejects(() => writes.service.authorize(request()), (error) => error.code === 'gh3-security-emergency-disabled'); assert.equal(writes.calls.length, 0); const reads = harness({ emergencyMode: () => 'read-only' }); const result = await reads.service.authorize(request({ capability: 'github.repository.read' })); assert.equal(result.relation, 'can_read'); });
test('GH3.11: disabled emergency mode blocks reads and writes', async () => { const { service, calls } = harness({ emergencyMode: () => 'disabled' }); await assert.rejects(() => service.authorize(request({ capability: 'github.repository.read' })), (error) => error.code === 'gh3-security-emergency-disabled'); assert.equal(calls.length, 0); });
test('GH3.11: Tier 3 requires separate request-bound confirmation', async () => { const { service, calls } = harness(); await assert.rejects(() => service.authorize(request({ capability: 'github.release.write' })), (error) => error.code === 'gh3-security-separate-confirmation-required'); assert.equal(calls.length, 0); const allowed = await service.authorize(request({ capability: 'github.release.write', confirmation: { confirmed: true, requestId: 'request-gh311' } })); assert.equal(allowed.riskTier, 3); });
test('GH3.11: Tier 4 additionally requires Owner Security', async () => { const { service } = harness(); await assert.rejects(() => service.authorize(request({ capability: 'github.repository.admin', confirmation: { confirmed: true, requestId: 'request-gh311' } })), (error) => error.code === 'gh3-security-owner-control-required'); const result = await service.authorize(request({ capability: 'github.repository.admin', ownerSecurityRequired: true, confirmation: { confirmed: true, requestId: 'request-gh311' } })); assert.equal(result.riskTier, 4); });
test('GH3.11: revoked authority, ACS denial, rate limit and Action Gate denial fail closed', async () => { const denied = [harness({ accessControl: { async assertAllowed() { return { allowed: false }; } } }), harness({ resourceAuthority: { async checkAuthority() { return { allowed: false, reason: 'revoked' }; } } }), harness({ rateLimiter: { async consume() { return { allowed: false }; } } }), harness({ actionGate: { evaluate() { return { outcome: 'deny', authorized: false }; } } })]; const codes = ['gh3-security-acs-denied','gh3-security-resource-authority-denied','gh3-security-rate-limited','gh3-security-action-gate-denied']; for (let index = 0; index < denied.length; index++) await assert.rejects(() => denied[index].service.authorize(request()), (error) => error.code === codes[index]); });
test('GH3.11: audit failure blocks protected execution and secret-shaped fields are redacted', async () => { const broken = harness({ audit: async () => { throw new Error('down'); } }); await assert.rejects(() => broken.service.execute(request(), async () => ({ status: 'should-not-run' })), (error) => error.code === 'gh3-security-audit-unavailable'); assert.equal(broken.calls.some(([name]) => name === 'credential'), false); const events = []; const safe = harness({ audit: async (event) => events.push(event) }); await assert.rejects(() => safe.service.execute(request(), async () => { const error = new Error('failed'); error.code = 'token-secret-value'; throw error; }), /failed/); assert.equal(JSON.stringify(events).includes('installation-secret'), false); });
