import test from 'node:test';
import assert from 'node:assert/strict';
import { createGitHubCollaborationService } from '../src/githubDevelopment/githubCollaborationService.js';

const SHA = 'a'.repeat(40);
function response(body, status = 200) { return { ok: status >= 200 && status < 300, status, async json() { return body; } }; }
function fixture(routes, calls = [], providerCalls = []) { return createGitHubCollaborationService({ clock: () => new Date('2026-08-20T12:00:00Z'), githubAppProvider: { async withInstallationToken(input) { providerCalls.push(input); return input.operation('secret-token'); } }, fetchImpl: async (url, init) => { const path = `${new URL(url).pathname}${new URL(url).search}`; const body = init.body ? JSON.parse(init.body) : null; calls.push({ path, method: init.method, body, headers: init.headers }); const route = routes.find((item) => (typeof item.path === 'string' ? path === item.path : item.path.test(path)) && (!item.method || item.method === init.method)); if (!route) throw new Error(`unexpected ${init.method} ${path}`); return response(route.body, route.status ?? 200); } }); }
const repo = { owner: 'acme', name: 'project' };

test('PR creation binds canonical base/head and idempotency marker', async () => { const calls = []; const providerCalls = []; const service = fixture([{ path: /\/pulls\?state=open/, body: [] }, { path: '/repos/acme/project/pulls', method: 'POST', body: { number: 7, html_url: 'https://example/pr/7' }, status: 201 }], calls, providerCalls); const result = await service.upsertPullRequest({ connectionId: 'github:1', repository: repo, baseBranch: 'dev/sg2.1-semantic', headBranch: 'dev/gh3.6', title: 'GH3.6', idempotencyKey: 'task-1' }); assert.equal(result.pullNumber, 7); assert.equal(providerCalls[0].capability, 'github.pull-request.write'); assert.match(calls[1].body.body, /sg-idempotency:task-1/); assert.equal(calls[1].body.draft, true); assert.equal(JSON.stringify(result).includes('secret-token'), false); });

test('duplicate and ambiguous PR retries do not create another PR', async () => { const canonical = { number: 7, title: 'GH3.6', body: '<!-- sg-idempotency:task-1 -->', base: { ref: 'base' }, head: { ref: 'head', repo: { full_name: 'acme/project' } } }; const reused = fixture([{ path: /\/pulls\?state=open/, body: [canonical] }]); const result = await reused.upsertPullRequest({ connectionId: 'c', repository: repo, baseBranch: 'base', headBranch: 'head', title: 'GH3.6', idempotencyKey: 'task-1' }); assert.equal(result.reused, true); const ambiguous = fixture([{ path: /\/pulls\?state=open/, body: [canonical, { ...canonical, number: 8 }] }]); await assert.rejects(() => ambiguous.upsertPullRequest({ connectionId: 'c', repository: repo, baseBranch: 'base', headBranch: 'head', title: 'GH3.6', idempotencyKey: 'task-1' }), (error) => error.code === 'gh3-collaboration-ambiguous-retry'); });

test('review reads are bounded and replies are idempotent', async () => { const service = fixture([{ path: '/repos/acme/project/pulls/7/reviews?per_page=100', body: [{ id: 3 }] }, { path: '/repos/acme/project/pulls/7/comments?per_page=100', body: [{ id: 4, body: 'fix', path: 'src/a.js', user: { login: 'reviewer' } }] }, { path: '/repos/acme/project/pulls/7/comments?per_page=100', body: [] }, { path: '/repos/acme/project/pulls/7/comments/4/replies', method: 'POST', body: { id: 5 }, status: 201 }]); const threads = await service.readReviewThreads({ connectionId: 'c', repository: repo, pullNumber: 7 }); assert.equal(threads.untrustedExternalData, true); assert.equal(threads.comments[0].author, 'reviewer'); const reply = await service.replyToReview({ connectionId: 'c', repository: repo, pullNumber: 7, commentId: 4, body: 'Applied', idempotencyKey: 'reply-1' }); assert.equal(reply.commentId, 5); });

test('review thread resolution requires approval and verifies repository identity', async () => { const denied = fixture([]); await assert.rejects(() => denied.resolveReviewThread({ connectionId: 'c', repository: repo, threadNodeId: 'PRRT_1' }), (error) => error.code === 'gh3-collaboration-separate-approval-required'); const service = fixture([{ path: '/graphql', method: 'POST', body: { data: { resolveReviewThread: { thread: { id: 'PRRT_1', isResolved: true, repository: { nameWithOwner: 'acme/project' } } } } } }]); const result = await service.resolveReviewThread({ connectionId: 'c', repository: repo, threadNodeId: 'PRRT_1', separateApproval: true }); assert.equal(result.resolved, true); });

test('issues support labels and milestones with duplicate-safe retry', async () => { const calls = []; const service = fixture([{ path: '/repos/acme/project/issues?state=all&per_page=100', body: [] }, { path: '/repos/acme/project/issues', method: 'POST', body: { number: 11 }, status: 201 }], calls); const result = await service.upsertIssue({ connectionId: 'c', repository: repo, title: 'Track GH3.6', labels: ['gh3', 'gh3'], milestone: 2, idempotencyKey: 'issue-1' }); assert.equal(result.issueNumber, 11); assert.deepEqual(calls[1].body.labels, ['gh3']); assert.equal(calls[1].body.milestone, 2); });

test('release and tag require separate approval and reject conflicting tag target', async () => { const denied = fixture([]); await assert.rejects(() => denied.createTagAndRelease({ connectionId: 'c', repository: repo, tagName: 'v1', targetSha: SHA, title: 'v1', idempotencyKey: 'r1' }), (error) => error.code === 'gh3-collaboration-separate-approval-required'); const conflict = fixture([{ path: '/repos/acme/project/releases/tags/v1', body: {}, status: 404 }, { path: '/repos/acme/project/git/ref/tags/v1', body: { object: { sha: 'b'.repeat(40) } } }]); await assert.rejects(() => conflict.createTagAndRelease({ connectionId: 'c', repository: repo, tagName: 'v1', targetSha: SHA, title: 'v1', idempotencyKey: 'r1', separateApproval: true }), (error) => error.code === 'gh3-collaboration-tag-conflict'); });

test('release retry reuses exact identity and ambiguous identity fails closed', async () => { const existing = { id: 9, target_commitish: SHA, body: '<!-- sg-idempotency:r1 -->' }; const service = fixture([{ path: '/repos/acme/project/releases/tags/v1', body: existing }, { path: '/repos/acme/project/git/ref/tags/v1', body: { object: { sha: SHA } } }]); const result = await service.createTagAndRelease({ connectionId: 'c', repository: repo, tagName: 'v1', targetSha: SHA, title: 'v1', idempotencyKey: 'r1', separateApproval: true }); assert.equal(result.reused, true); });
