import { randomUUID } from 'node:crypto';
import { assertWorkspaceId,assertEntityId,boundedText,isoTime } from './workspaceOperationsContract.js';
const DOMAINS=new Set(['content','media','poll','test','form','submission','event','registration','feedback','faq','onboarding','moderation','case','decision','content-plan','summary','unanswered','task-link','export','analytics']);
const freeze=(v)=>{if(!v||typeof v!=='object'||Object.isFrozen(v))return v;for(const x of Object.values(v))freeze(x);return Object.freeze(v);};
const domain=(v)=>{v=boundedText(v,'domain',32);if(!DOMAINS.has(v))throw new TypeError(`unsupported domain: ${v}`);return v;};
const row=(r)=>r?freeze({workspaceId:r.workspace_id,domain:r.domain,recordId:r.record_id,status:r.status,visibility:r.visibility,privacyClass:r.privacy_class,actorGlobalUserId:r.actor_global_user_id,payload:r.payload??{},version:Number(r.version),idempotencyKey:r.idempotency_key??null,createdAt:isoTime(r.created_at),updatedAt:isoTime(r.updated_at)}):null;
export function createPostgresTelegramWorkspaceOperationsStore(database){
if(typeof database?.query!=='function'||typeof database?.transaction!=='function')throw new TypeError('started PostgreSQL database is required');
async function ensureWorkspace(workspaceId,db=database){const id=assertWorkspaceId(workspaceId),r=await db.query('SELECT workspace_id FROM telegram_workspaces WHERE workspace_id=$1',[id]);if(r.rowCount!==1)throw Object.assign(new Error('workspace not found'),{code:'twm-cross-workspace-denied'});return id;}
async function createRecord(x,db=database){const wid=await ensureWorkspace(x.workspaceId,db),d=domain(x.domain),rid=assertEntityId(x.recordId),idem=x.idempotencyKey?boundedText(x.idempotencyKey,'idempotencyKey',300):null;if(idem){const e=await db.query('SELECT * FROM telegram_workspace_domain_records WHERE workspace_id=$1 AND idempotency_key=$2',[wid,idem]);if(e.rowCount)return row(e.rows[0]);}const r=await db.query(`INSERT INTO telegram_workspace_domain_records(workspace_id,domain,record_id,status,visibility,privacy_class,actor_global_user_id,payload,version,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,1,$9) RETURNING *`,[wid,d,rid,boundedText(x.status??'active','status',40),boundedText(x.visibility??'workspace','visibility',40),boundedText(x.privacyClass??'workspace','privacyClass',40),boundedText(x.actorGlobalUserId,'actorGlobalUserId',200),JSON.stringify(x.payload??{}),idem]);return row(r.rows[0]);}
async function getRecord(x,db=database){const r=await db.query('SELECT * FROM telegram_workspace_domain_records WHERE workspace_id=$1 AND domain=$2 AND record_id=$3',[assertWorkspaceId(x.workspaceId),domain(x.domain),assertEntityId(x.recordId)]);return row(r.rows[0]);}
async function updateRecord(x,db=database){const wid=assertWorkspaceId(x.workspaceId),d=domain(x.domain),rid=assertEntityId(x.recordId);return db.transaction(async tx=>{const l=await tx.query('SELECT * FROM telegram_workspace_domain_records WHERE workspace_id=$1 AND domain=$2 AND record_id=$3 FOR UPDATE',[wid,d,rid]);if(l.rowCount!==1)throw Object.assign(new Error('record not found'),{code:'twm-domain-record-not-found'});const c=l.rows[0];if(x.expectedVersion!=null&&Number(x.expectedVersion)!==Number(c.version))throw Object.assign(new Error('version conflict'),{code:'twm-domain-version-conflict'});const r=await tx.query(`UPDATE telegram_workspace_domain_records SET status=$4,visibility=$5,privacy_class=$6,actor_global_user_id=$7,payload=$8::jsonb,version=version+1,updated_at=now() WHERE workspace_id=$1 AND domain=$2 AND record_id=$3 RETURNING *`,[wid,d,rid,x.status??c.status,x.visibility??c.visibility,x.privacyClass??c.privacy_class,boundedText(x.actorGlobalUserId,'actorGlobalUserId',200),JSON.stringify(x.payload===undefined?c.payload:x.payload)]);return row(r.rows[0]);});}
async function listRecords({workspaceId,domain:raw,status=null,limit=100},db=database){const n=Math.max(1,Math.min(Number(limit)||100,500)),r=await db.query('SELECT * FROM telegram_workspace_domain_records WHERE workspace_id=$1 AND domain=$2 AND ($3::text IS NULL OR status=$3) ORDER BY created_at,record_id LIMIT $4',[assertWorkspaceId(workspaceId),domain(raw),status,n]);return freeze(r.rows.map(row));}
async function countRecords({workspaceId,domain:raw,status=null,from=null,to=null},db=database){const r=await db.query('SELECT COUNT(*)::bigint AS count FROM telegram_workspace_domain_records WHERE workspace_id=$1 AND domain=$2 AND ($3::text IS NULL OR status=$3) AND ($4::timestamptz IS NULL OR created_at >= $4) AND ($5::timestamptz IS NULL OR created_at < $5)',[assertWorkspaceId(workspaceId),domain(raw),status,from?isoTime(from):null,to?isoTime(to):null]);return Number(r.rows[0]?.count??0);}
async function findPollByTelegramId(id,db=database){const r=await db.query("SELECT * FROM telegram_workspace_domain_records WHERE domain='poll' AND payload->>'telegramPollId'=$1 ORDER BY created_at DESC LIMIT 2",[boundedText(String(id),'telegramPollId',300)]);if(r.rowCount>1)throw Object.assign(new Error('Telegram poll id scope conflict'),{code:'twm-poll-scope-conflict'});return row(r.rows[0]);}
async function appendEvent(x,db=database){const wid=await ensureWorkspace(x.workspaceId,db),key=boundedText(x.eventKey,'eventKey',300),r=await db.query(`INSERT INTO telegram_workspace_domain_events(event_id,workspace_id,event_key,event_type,record_domain,record_id,actor_global_user_id,evidence,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9) ON CONFLICT(workspace_id,event_key) DO NOTHING RETURNING event_id`,[randomUUID(),wid,key,boundedText(x.eventType,'eventType',80),x.recordDomain?domain(x.recordDomain):null,x.recordId?assertEntityId(x.recordId):null,x.actorGlobalUserId??null,JSON.stringify(x.evidence??{}),isoTime(x.occurredAt??new Date())]);return freeze({inserted:r.rowCount===1,deduplicated:r.rowCount===0,workspaceId:wid,eventKey:key});}
async function aggregateEvents({workspaceId,from=null,to=null},db=database){const r=await db.query(`SELECT event_type,COUNT(*)::bigint AS count FROM telegram_workspace_domain_events WHERE workspace_id=$1 AND ($2::timestamptz IS NULL OR occurred_at >= $2) AND ($3::timestamptz IS NULL OR occurred_at < $3) GROUP BY event_type ORDER BY event_type`,[assertWorkspaceId(workspaceId),from?isoTime(from):null,to?isoTime(to):null]);return freeze(Object.fromEntries(r.rows.map(x=>[x.event_type,Number(x.count)])));}
async function aggregateEventActors({workspaceId,eventTypes=[],from=null,to=null},db=database){const types=Array.isArray(eventTypes)?eventTypes.map((value)=>boundedText(value,'eventType',80)):[];const r=await db.query(`SELECT COUNT(DISTINCT actor_global_user_id)::bigint AS unique_actors,COUNT(*)::bigint AS interaction_events FROM telegram_workspace_domain_events WHERE workspace_id=$1 AND actor_global_user_id IS NOT NULL AND (cardinality($2::text[]) = 0 OR event_type = ANY($2::text[])) AND ($3::timestamptz IS NULL OR occurred_at >= $3) AND ($4::timestamptz IS NULL OR occurred_at < $4)`,[assertWorkspaceId(workspaceId),types,from?isoTime(from):null,to?isoTime(to):null]);return freeze({uniqueActors:Number(r.rows[0]?.unique_actors??0),interactionEvents:Number(r.rows[0]?.interaction_events??0)});}
async function registerEventParticipant({workspaceId,eventId,participantGlobalUserId,registrationId,idempotencyKey}){const wid=assertWorkspaceId(workspaceId),eid=assertEntityId(eventId),actor=boundedText(participantGlobalUserId,'participantGlobalUserId',200),idem=boundedText(idempotencyKey,'idempotencyKey',300);return database.transaction(async tx=>{await ensureWorkspace(wid,tx);const prior=await tx.query('SELECT * FROM telegram_workspace_domain_records WHERE workspace_id=$1 AND idempotency_key=$2',[wid,idem]);if(prior.rowCount)return freeze({registration:row(prior.rows[0]),deduplicated:true,promoted:null});const er=await tx.query("SELECT * FROM telegram_workspace_domain_records WHERE workspace_id=$1 AND domain='event' AND record_id=$2 FOR UPDATE",[wid,eid]);if(er.rowCount!==1||er.rows[0].status!=='open')throw Object.assign(new Error('event unavailable'),{code:'twm-event-unavailable'});const cap=er.rows[0].payload?.capacity==null?null:Number(er.rows[0].payload.capacity),count=await tx.query("SELECT COUNT(*)::bigint AS count FROM telegram_workspace_domain_records WHERE workspace_id=$1 AND domain='registration' AND payload->>'eventId'=$2 AND status IN ('REGISTERED','CONFIRMED','ATTENDED')",[wid,eid]),active=Number(count.rows[0]?.count??0),state=cap!==null&&active>=cap?(er.rows[0].payload?.waitlist===true?'WAITLISTED':null):'REGISTERED';if(!state)throw Object.assign(new Error('event capacity reached'),{code:'twm-event-capacity-reached'});const registration=await createRecord({workspaceId:wid,domain:'registration',recordId:registrationId,status:state,visibility:'operators',privacyClass:'private',actorGlobalUserId:actor,payload:{eventId:eid,participantGlobalUserId:actor},idempotencyKey:idem},tx);return freeze({registration,deduplicated:false,promoted:null});});}
async function cancelEventRegistration({workspaceId,registrationId,actorGlobalUserId}){const wid=assertWorkspaceId(workspaceId),rid=assertEntityId(registrationId),actor=boundedText(actorGlobalUserId,'actorGlobalUserId',200);return database.transaction(async tx=>{const cur=await tx.query("SELECT * FROM telegram_workspace_domain_records WHERE workspace_id=$1 AND domain='registration' AND record_id=$2 FOR UPDATE",[wid,rid]);if(cur.rowCount!==1)throw Object.assign(new Error('registration not found'),{code:'twm-domain-record-not-found'});const c=cur.rows[0],eid=c.payload?.eventId;await tx.query("SELECT record_id FROM telegram_workspace_domain_records WHERE workspace_id=$1 AND domain='event' AND record_id=$2 FOR UPDATE",[wid,eid]);const cancelled=await tx.query("UPDATE telegram_workspace_domain_records SET status='CANCELLED',actor_global_user_id=$3,version=version+1,updated_at=now() WHERE workspace_id=$1 AND domain='registration' AND record_id=$2 RETURNING *",[wid,rid,actor]);let promoted=null;if(['REGISTERED','CONFIRMED'].includes(c.status)){const waiter=await tx.query("SELECT * FROM telegram_workspace_domain_records WHERE workspace_id=$1 AND domain='registration' AND payload->>'eventId'=$2 AND status='WAITLISTED' ORDER BY created_at,record_id LIMIT 1 FOR UPDATE",[wid,eid]);if(waiter.rowCount){const p=await tx.query("UPDATE telegram_workspace_domain_records SET status='REGISTERED',version=version+1,updated_at=now() WHERE workspace_id=$1 AND domain='registration' AND record_id=$2 RETURNING *",[wid,waiter.rows[0].record_id]);promoted=row(p.rows[0]);}}return freeze({registration:row(cancelled.rows[0]),promoted});});}
async function saveAnalyticsSnapshot({workspaceId,snapshotId=null,from=null,to=null,metrics={},evidenceVersion='twm1.15.v2'},db=database){const wid=await ensureWorkspace(workspaceId,db),sid=assertEntityId(snapshotId??`analytics_${randomUUID().replaceAll('-','')}`),r=await db.query(`INSERT INTO telegram_workspace_analytics_snapshots(snapshot_id,workspace_id,window_from,window_to,metrics,evidence_version) VALUES($1,$2,$3,$4,$5::jsonb,$6) ON CONFLICT(snapshot_id) DO UPDATE SET metrics=EXCLUDED.metrics,evidence_version=EXCLUDED.evidence_version RETURNING *`,[sid,wid,from?isoTime(from):null,to?isoTime(to):null,JSON.stringify(metrics),boundedText(evidenceVersion,'evidenceVersion',80)]);return freeze({snapshotId:r.rows[0].snapshot_id,workspaceId:wid,from:r.rows[0].window_from?isoTime(r.rows[0].window_from):null,to:r.rows[0].window_to?isoTime(r.rows[0].window_to):null,metrics:r.rows[0].metrics??{},evidenceVersion:r.rows[0].evidence_version,createdAt:isoTime(r.rows[0].created_at)});}
return Object.freeze({createRecord,getRecord,updateRecord,listRecords,countRecords,findPollByTelegramId,appendEvent,aggregateEvents,aggregateEventActors,registerEventParticipant,cancelEventRegistration,saveAnalyticsSnapshot});}
export const TELEGRAM_WORKSPACE_OPERATION_DOMAINS=Object.freeze([...DOMAINS]);
