import { randomUUID, createHash } from 'node:crypto';
import { assertWorkspaceId, boundedText } from './workspaceOperationsContract.js';
export function deepFreeze(value){if(!value||typeof value!=='object'||Object.isFrozen(value))return value;for(const child of Object.values(value))deepFreeze(child);return Object.freeze(value);}
export const uid=(prefix)=>`${prefix}_${randomUUID().replaceAll('-','')}`;
export const hashKey=(parts)=>createHash('sha256').update(parts.map(x=>String(x??'')).join('|')).digest('hex');
export function fail(message,code,extra={}){throw Object.assign(new Error(message),{code,...extra});}
export function scopeFor(ctx,projectScope){return Object.freeze({userScope:ctx.actorGlobalUserId,projectScope,groupScope:ctx.workspaceId,threadScope:null});}
export function createWorkspaceOperationsCore({store,workspaceRegistry,authorityResolver,mutationGate,botCapabilityService=null,projectScope='sg2.1',audit=async()=>{}}={}){
 if(typeof workspaceRegistry?.getWorkspace!=='function')throw new TypeError('workspaceRegistry.getWorkspace is required');if(typeof authorityResolver?.verify!=='function')throw new TypeError('authorityResolver.verify is required');if(typeof mutationGate?.evaluateDomainMutation!=='function')throw new TypeError('mutationGate.evaluateDomainMutation is required');if(botCapabilityService!==null&&typeof botCapabilityService?.requireCapabilities!=='function')throw new TypeError('botCapabilityService.requireCapabilities is required');const project=boundedText(projectScope,'projectScope',200);
 async function workspace(workspaceId){const id=assertWorkspaceId(workspaceId),row=await workspaceRegistry.getWorkspace(id);if(!row)fail('workspace not found','twm-domain-workspace-not-found');return row;}
 async function authority(ctx,action='workspace:view',fresh=false){const decision=await authorityResolver.verify({workspaceId:assertWorkspaceId(ctx.workspaceId),telegramUserId:String(ctx.telegramUserId),expectedGlobalUserId:boundedText(ctx.actorGlobalUserId,'actorGlobalUserId',200),requestedAction:action,forceFresh:fresh});if(!decision?.allowed)fail('workspace authority denied',decision?.reason??'twm-domain-authority-denied');return decision;}
 async function capabilities(workspaceId,requiredCapabilities){if(!botCapabilityService)return null;return botCapabilityService.requireCapabilities({workspaceId,requiredCapabilities,requireFresh:true});}
 async function gate(ctx,{operation,domain,recordId=null,risk='low',confirmationRequired=false,authorityAction='workspace:configure',requiredPermission='workspace:configure'},work){const auth=await authority(ctx,authorityAction,true),requestId=ctx.requestId??`twm:${randomUUID()}`,traceId=ctx.traceId??requestId,confirmation=ctx.confirmation?.confirmed===true&&ctx.confirmation?.requestId===requestId?ctx.confirmation:(confirmationRequired?null:{confirmed:true,requestId});await mutationGate.evaluateDomainMutation({operation,domain,recordId,workspaceId:ctx.workspaceId,actorGlobalUserId:ctx.actorGlobalUserId,traceId,requestId,risk,confirmationRequired,authority:auth,confirmation,requiredPermission});const result=await work({auth,requestId,traceId});try{await audit(deepFreeze({eventClass:'telegram_workspace_operations',operation,domain,recordId:recordId??result?.recordId??null,workspaceId:ctx.workspaceId,actorGlobalUserId:ctx.actorGlobalUserId,traceId,requestId,outcome:'success'}));}catch{}return result;}
 return Object.freeze({store,project,workspace,authority,capabilities,gate});
}
