const ID_RE = /^tgw_[A-Za-z0-9_-]{8,}$/;
const ENTITY_ID_RE = /^[a-z][a-z0-9_-]{2,127}$/;
export const TWM_CONTENT_KINDS = Object.freeze(['text','photo','video','document','poll','quiz','test']);
export const TWM_CONTENT_STATES = Object.freeze(['draft','scheduled','published','cancelled','failed']);
export const TWM_CASE_STATES = Object.freeze(['OPEN','TRIAGED','IN_PROGRESS','WAITING','RESOLVED','CLOSED']);
export const TWM_REGISTRATION_STATES = Object.freeze(['REGISTERED','CONFIRMED','WAITLISTED','CANCELLED','ATTENDED','NO_SHOW']);
export const TWM_VISIBILITY = Object.freeze(['workspace','operators','owner','private']);
export const TWM_PRIVACY = Object.freeze(['public','workspace','private','anonymous']);
function required(value,name){if(typeof value!=='string'||value.trim()==='')throw new TypeError(`${name} is required`);return value.trim();}
export function assertWorkspaceId(value){const id=required(value,'workspaceId');if(!ID_RE.test(id))throw Object.assign(new Error('workspaceId must be canonical'),{code:'twm-cross-workspace-denied'});return id;}
export function assertEntityId(value,name='entityId'){const id=required(value,name);if(!ENTITY_ID_RE.test(id))throw new TypeError(`${name} is invalid`);return id;}
export function boundedText(value,name,max=4096,{allowEmpty=false}={}){const text=typeof value==='string'?value.trim():'';if(!allowEmpty&&!text)throw new TypeError(`${name} is required`);if(text.length>max)throw Object.assign(new Error(`${name} is too long`),{code:'twm-domain-value-too-large'});return text;}
export function boundedArray(value,name,max=100){if(!Array.isArray(value))throw new TypeError(`${name} must be an array`);if(value.length>max)throw Object.assign(new Error(`${name} has too many items`),{code:'twm-domain-value-too-large'});return value;}
export function enumValue(value,values,name){const normalized=required(value,name);if(!values.includes(normalized))throw new TypeError(`unsupported ${name}: ${normalized}`);return normalized;}
export function isoTime(value,name='time',{nullable=false}={}){if(value==null&&nullable)return null;const date=value instanceof Date?value:new Date(value);if(!Number.isFinite(date.getTime()))throw new TypeError(`${name} must be a valid date`);return date.toISOString();}
export function canonicalOptions(options,{min=2,max=10}={}){const rows=boundedArray(options,'options',max).map((item,index)=>Object.freeze({index,text:boundedText(typeof item==='string'?item:item?.text,`options[${index}]`,100)}));if(rows.length<min)throw new TypeError(`options must contain at least ${min} items`);return Object.freeze(rows);}
export function deterministicPollStatistics(options=[],totalVoterCount=null){const rows=boundedArray(options,'options',100).map((option,index)=>{const count=Number(option?.voter_count??option?.voterCount??0);if(!Number.isSafeInteger(count)||count<0)throw new TypeError(`options[${index}] voter count is invalid`);return Object.freeze({index,text:boundedText(option?.text??String(index+1),`options[${index}].text`,100),count});});const sum=rows.reduce((a,r)=>a+r.count,0),total=totalVoterCount==null?sum:Number(totalVoterCount);if(!Number.isSafeInteger(total)||total<0)throw new TypeError('totalVoterCount is invalid');return Object.freeze({totalVoterCount:total,optionVoteCount:sum,options:Object.freeze(rows.map(row=>Object.freeze({...row,percentage:total===0?0:Number(((row.count/total)*100).toFixed(4))})))});}
export function deterministicTestScore(questions,answers){const qs=boundedArray(questions,'questions',100),map=new Map((Array.isArray(answers)?answers:[]).map(a=>[String(a.questionId),Number(a.optionIndex)]));let correct=0;const results=qs.map((q,index)=>{const id=assertEntityId(q.id??`q_${index+1}`,`questions[${index}].id`),expected=Number(q.correctOptionIndex);if(!Number.isSafeInteger(expected)||expected<0)throw new TypeError(`questions[${index}].correctOptionIndex is invalid`);const actual=map.has(id)?map.get(id):null,isCorrect=actual===expected;if(isCorrect)correct++;return Object.freeze({questionId:id,optionIndex:actual,correctOptionIndex:expected,correct:isCorrect});});return Object.freeze({total:qs.length,answered:results.filter(x=>x.optionIndex!==null).length,correct,scorePercent:qs.length===0?0:Number(((correct/qs.length)*100).toFixed(4)),results:Object.freeze(results)});}
export function assertSameWorkspace(...records){const ids=records.filter(Boolean).map(x=>assertWorkspaceId(x.workspaceId));if(ids.length&&ids.some(id=>id!==ids[0]))throw Object.assign(new Error('cross-workspace reference denied'),{code:'twm-cross-workspace-denied'});return ids[0]??null;}
