function required(value,name){if(typeof value!=='string'||value.trim()==='')throw new TypeError(`${name} is required`);return value.trim();}
function project(value){return required(value,'projectKey').toLowerCase();}
function repository(value){return required(value,'repository').toLowerCase();}
function json(value){return JSON.stringify(value??{});}
function iso(value,name){const d=new Date(value);if(Number.isNaN(d.getTime()))throw new TypeError(`${name} must be ISO timestamp`);return d.toISOString();}
function commitSha(value,name='commitSha'){const sha=required(value,name).toLowerCase();if(!/^[a-f0-9]{40}$/.test(sha))throw new TypeError(`${name} must be a full immutable git SHA`);return sha;}

export function createPostgresContinuousIngestionStore(database){
  if(!database?.query||!database?.transaction)throw new TypeError('started PostgreSQL database is required');
  async function getState({projectKey,repository:repo},db=database){const result=await db.query('SELECT * FROM pdk4_continuous_ingestion_state WHERE project_key=$1 AND repository=$2',[project(projectKey),repository(repo)]);if(result.rowCount===0)return null;const row=result.rows[0];return Object.freeze({projectKey:row.project_key,repository:row.repository,bootstrapLastSourceId:row.bootstrap_last_source_id,lastSourceId:row.last_source_id,lastCommitSha:row.last_commit_sha,processedCount:Number(row.processed_count),lastProcessedAt:row.last_processed_at?.toISOString?.()??row.last_processed_at??null,createdAt:row.created_at?.toISOString?.()??row.created_at,updatedAt:row.updated_at?.toISOString?.()??row.updated_at});}
  async function ensureState({projectKey,repository:repo,bootstrapLastSourceId,bootstrapLastCommitSha},db=database){const p=project(projectKey),r=repository(repo),anchor=required(bootstrapLastSourceId,'bootstrapLastSourceId'),sha=commitSha(bootstrapLastCommitSha,'bootstrapLastCommitSha');await db.query('INSERT INTO pdk4_continuous_ingestion_state(project_key,repository,bootstrap_last_source_id,last_source_id,last_commit_sha) VALUES ($1,$2,$3,$3,$4) ON CONFLICT(project_key,repository) DO NOTHING',[p,r,anchor,sha]);return getState({projectKey:p,repository:r},db);}
  async function reanchorState({projectKey,repository:repo,bootstrapLastSourceId,bootstrapLastCommitSha},db=database){const p=project(projectKey),r=repository(repo),anchor=required(bootstrapLastSourceId,'bootstrapLastSourceId'),sha=commitSha(bootstrapLastCommitSha,'bootstrapLastCommitSha');return db.transaction(async tx=>{await tx.query('SELECT project_key FROM pdk4_continuous_ingestion_state WHERE project_key=$1 AND repository=$2 FOR UPDATE',[p,r]);await tx.query(`INSERT INTO pdk4_continuous_ingestion_state(project_key,repository,bootstrap_last_source_id,last_source_id,last_commit_sha)
      VALUES ($1,$2,$3,$3,$4)
      ON CONFLICT(project_key,repository) DO UPDATE SET bootstrap_last_source_id=EXCLUDED.bootstrap_last_source_id,last_source_id=EXCLUDED.last_source_id,last_commit_sha=EXCLUDED.last_commit_sha,updated_at=now()`,[p,r,anchor,sha]);return getState({projectKey:p,repository:r},tx);});}
  async function isProcessed({projectKey,repository:repo,sourceId},db=database){const result=await db.query('SELECT 1 FROM pdk4_continuous_processed_sources WHERE project_key=$1 AND repository=$2 AND source_id=$3',[project(projectKey),repository(repo),required(sourceId,'sourceId')]);return result.rowCount===1;}
  async function recordTrigger({projectKey,repository:repo,triggerId,triggerType,metadata={}},db=database){const p=project(projectKey),r=repository(repo),id=required(triggerId,'triggerId'),type=required(triggerType,'triggerType');return db.transaction(async tx=>{const locked=await tx.query('SELECT status FROM pdk4_continuous_triggers WHERE project_key=$1 AND repository=$2 AND trigger_id=$3 FOR UPDATE',[p,r,id]);if(locked.rowCount===0){await tx.query("INSERT INTO pdk4_continuous_triggers(project_key,repository,trigger_id,trigger_type,status,metadata) VALUES ($1,$2,$3,$4,'processing',$5::jsonb)",[p,r,id,type,json(metadata)]);return Object.freeze({duplicate:false,retry:false});}const status=locked.rows[0].status;if(status==='failed'){await tx.query("UPDATE pdk4_continuous_triggers SET status='processing',trigger_type=$4,metadata=$5::jsonb,updated_at=now() WHERE project_key=$1 AND repository=$2 AND trigger_id=$3",[p,r,id,type,json(metadata)]);return Object.freeze({duplicate:false,retry:true});}return Object.freeze({duplicate:true,retry:false,status});});}
  async function completeTrigger({projectKey,repository:repo,triggerId},db=database){await db.query("UPDATE pdk4_continuous_triggers SET status='completed',updated_at=now() WHERE project_key=$1 AND repository=$2 AND trigger_id=$3 AND status='processing'",[project(projectKey),repository(repo),required(triggerId,'triggerId')]);}
  async function failTrigger({projectKey,repository:repo,triggerId},db=database){await db.query("UPDATE pdk4_continuous_triggers SET status='failed',updated_at=now() WHERE project_key=$1 AND repository=$2 AND trigger_id=$3 AND status='processing'",[project(projectKey),repository(repo),required(triggerId,'triggerId')]);}
  async function commitProcessed({projectKey,repository:repo,sourceId,sourceFingerprint,commitSha:commitShaInput,occurredAt,triggerId,metadata={}},db=database){const p=project(projectKey),r=repository(repo),sid=required(sourceId,'sourceId'),fp=required(sourceFingerprint,'sourceFingerprint'),sha=commitSha(commitShaInput);return db.transaction(async tx=>{const inserted=await tx.query('INSERT INTO pdk4_continuous_processed_sources(project_key,repository,source_id,source_fingerprint,commit_sha,occurred_at,trigger_id,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb) ON CONFLICT(project_key,repository,source_id) DO NOTHING RETURNING source_id',[p,r,sid,fp,sha,iso(occurredAt,'occurredAt'),required(triggerId,'triggerId'),json(metadata)]);if(inserted.rowCount===0)return Object.freeze({duplicate:true,state:await getState({projectKey:p,repository:r},tx)});await tx.query('UPDATE pdk4_continuous_ingestion_state SET last_source_id=$3,last_commit_sha=$4,processed_count=processed_count+1,last_processed_at=$5,updated_at=now() WHERE project_key=$1 AND repository=$2',[p,r,sid,sha,iso(occurredAt,'occurredAt')]);return Object.freeze({duplicate:false,state:await getState({projectKey:p,repository:r},tx)});});}
  async function countProcessed({projectKey,repository:repo},db=database){const result=await db.query('SELECT count(*)::int AS count FROM pdk4_continuous_processed_sources WHERE project_key=$1 AND repository=$2',[project(projectKey),repository(repo)]);return Number(result.rows[0].count);}
  return Object.freeze({getState,ensureState,reanchorState,isProcessed,recordTrigger,completeTrigger,failTrigger,commitProcessed,countProcessed});
}
