ALTER TABLE chat_meta
ADD COLUMN IF NOT EXISTS source_enabled BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE chat_meta
ADD COLUMN IF NOT EXISTS privacy_level TEXT NOT NULL DEFAULT 'private';

ALTER TABLE chat_meta
ADD COLUMN IF NOT EXISTS allow_quotes BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE chat_meta
ADD COLUMN IF NOT EXISTS allow_raw_snippets BOOLEAN NOT NULL DEFAULT false;