import { createGitHubRepositoryIdentity } from './githubDevelopmentContract.js';

const SHA = /^[0-9a-f]{40}$/u;
function fail(code, message, { status = null, retryable = false } = {}) { const error = new Error(message); error.name = 'GitHubActionsCIRepairError'; error.code = code; error.status = status; error.retryable = retryable; throw error; }
function required(value, field) { if (typeof value !== 'string' || value.trim() === '') fail('gh3-ci-input-invalid', `${field} is required`); return value.trim(); }
function fullSha(value, field) { const normalized = required(value, field).toLowerCase(); if (!SHA.test(normalized)) fail('gh3-ci-revision-invalid', `${field} must be a full SHA`); return normalized; }
function positive(value, field, max = Number.MAX_SAFE_INTEGER) { if (!Number.isInteger(value) || value < 1 || value > max) fail('gh3-ci-input-invalid', `${field} is invalid`); return value; }
function freeze(value) { if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value; for (const nested of Object.values(value)) freeze(nested); return Object.freeze(value); }
const actionable = new Set(['failure', 'timed_out', 'action_required']);

export function createGitHubActionsCIRepairService({ fetchImpl = globalThis.fetch, githubAppProvider, apiBaseUrl = 'https://api.github.com', clock = () => new Date(), maxRuns = 20, maxJobs = 100, maxLogChars = 50000 } = {}) {
  if (typeof fetchImpl !== 'function' || typeof clock !== 'function') throw new TypeError('invalid CI repair dependency');
  if (!githubAppProvider?.withInstallationToken) throw new TypeError('githubAppProvider.withInstallationToken is required');
  positive(maxRuns, 'maxRuns', 100); positive(maxJobs, 'maxJobs', 100); positive(maxLogChars, 'maxLogChars', 200000);
  const base = required(apiBaseUrl, 'apiBaseUrl').replace(/\/+$/u, '');
  const root = (repository) => `/repos/${encodeURIComponent(repository.owner)}/${encodeURIComponent(repository.name)}`;
  async function request(path, { token, method = 'GET', body = null, text = false } = {}) { let response; try { response = await fetchImpl(`${base}${path}`, { method, headers: { Accept: 'application/vnd.github+json', Authorization: `Bearer ${token}`, 'X-GitHub-Api-Version': '2022-11-28', 'User-Agent': 'sg-gh3-ci-repair', ...(body ? { 'Content-Type': 'application/json' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) }); } catch { fail('gh3-ci-provider-unavailable', 'GitHub Actions operation failed', { retryable: true }); } if (response?.status === 403) fail('gh3-ci-permission-denied', 'GitHub Actions permission is unavailable', { status: 403 }); if (!response?.ok) fail(`gh3-ci-http-${response?.status ?? 'unknown'}`, 'GitHub Actions operation was not successful', { status: response?.status ?? null, retryable: response?.status >= 500 }); if (response.status === 204) return null; try { return text ? await response.text() : await response.json(); } catch { fail('gh3-ci-response-invalid', 'GitHub Actions returned invalid data'); } }
  function authorized({ connectionId, repository: input, capability, permission, operation }) { const repository = createGitHubRepositoryIdentity(input); return githubAppProvider.withInstallationToken({ connectionId: required(connectionId, 'connectionId'), capability, repository, requiredProviderPermission: permission, operation: (token) => operation({ token, repository }) }); }

  async function inspectExactHead({ connectionId, repository, headSha, workflow = null } = {}) { const target = fullSha(headSha, 'headSha'); return authorized({ connectionId, repository, capability: 'github.actions.read', permission: 'actions', operation: async ({ token, repository: repo }) => { const data = await request(`${root(repo)}/actions/runs?head_sha=${target}&per_page=${maxRuns}`, { token }); const runs = (data?.workflow_runs ?? []).filter((run) => String(run.head_sha).toLowerCase() === target && (!workflow || run.name === workflow || String(run.workflow_id) === String(workflow))).slice(0, maxRuns); const normalized = []; for (const run of runs) { const jobsData = await request(`${root(repo)}/actions/runs/${positive(run.id, 'run.id')}/jobs?per_page=${maxJobs}`, { token }); const jobs = (jobsData?.jobs ?? []).filter((job) => !job.head_sha || String(job.head_sha).toLowerCase() === target).slice(0, maxJobs); normalized.push({ runId: run.id, workflow: run.name ?? String(run.workflow_id), status: run.status, conclusion: run.conclusion ?? null, headSha: target, url: run.html_url ?? null, jobs: jobs.map((job) => ({ jobId: job.id, name: job.name, status: job.status, conclusion: job.conclusion ?? null, url: job.html_url ?? null, steps: (job.steps ?? []).slice(0, 100).map((step) => ({ number: step.number, name: step.name, status: step.status, conclusion: step.conclusion ?? null })) })) }); } return freeze({ repository: repo, headSha: target, runs: normalized, exactHeadVerified: true, truncated: (data?.workflow_runs?.length ?? 0) > runs.length, observedAt: clock().toISOString() }); } }); }

  async function dispatchWorkflow({ connectionId, repository, workflowId, ref, expectedHeadSha, inputs = {}, idempotencyKey, attempt = 1, maxAttempts = 3 } = {}) { positive(attempt, 'attempt', positive(maxAttempts, 'maxAttempts', 20)); const expected = fullSha(expectedHeadSha, 'expectedHeadSha'); return authorized({ connectionId, repository, capability: 'github.actions.dispatch', permission: 'actions', operation: async ({ token, repository: repo }) => { const branch = required(ref, 'ref'); const refData = await request(`${root(repo)}/git/ref/heads/${branch.split('/').map(encodeURIComponent).join('/')}`, { token }); if (fullSha(refData?.object?.sha, 'ref.object.sha') !== expected) fail('gh3-ci-stale-head', 'workflow ref no longer matches exact target HEAD'); const key = required(idempotencyKey, 'idempotencyKey'); const runs = await request(`${root(repo)}/actions/workflows/${encodeURIComponent(required(workflowId, 'workflowId'))}/runs?branch=${encodeURIComponent(branch)}&per_page=${maxRuns}`, { token }); const duplicate = (runs?.workflow_runs ?? []).find((run) => String(run.head_sha).toLowerCase() === expected && run?.display_title?.includes(`[sg:${key}]`)); if (duplicate) return freeze({ repository: repo, headSha: expected, runId: duplicate.id, reused: true, mutated: false }); await request(`${root(repo)}/actions/workflows/${encodeURIComponent(workflowId)}/dispatches`, { token, method: 'POST', body: { ref: branch, inputs: { ...inputs, sg_idempotency_key: key } } }); return freeze({ repository: repo, headSha: expected, dispatched: true, reused: false, mutated: true, attempt, maxAttempts }); } }); }

  async function rerunFailed({ connectionId, repository, runId, expectedHeadSha, idempotencyKey, attempt = 1, maxAttempts = 3 } = {}) { positive(attempt, 'attempt', positive(maxAttempts, 'maxAttempts', 20)); return authorized({ connectionId, repository, capability: 'github.actions.rerun', permission: 'actions', operation: async ({ token, repository: repo }) => { const id = positive(runId, 'runId'); const expected = fullSha(expectedHeadSha, 'expectedHeadSha'); const run = await request(`${root(repo)}/actions/runs/${id}`, { token }); if (fullSha(run?.head_sha, 'run.head_sha') !== expected) fail('gh3-ci-wrong-revision', 'CI run belongs to another revision'); if (!actionable.has(run.conclusion)) fail('gh3-ci-rerun-not-actionable', 'CI run is not eligible for failed-job rerun'); await request(`${root(repo)}/actions/runs/${id}/rerun-failed-jobs`, { token, method: 'POST', body: { enable_debug_logging: false } }); return freeze({ repository: repo, runId: id, headSha: expected, idempotencyKey: required(idempotencyKey, 'idempotencyKey'), rerun: true, attempt, maxAttempts }); } }); }

  async function firstActionableFailure({ connectionId, repository, runId, expectedHeadSha } = {}) { return authorized({ connectionId, repository, capability: 'github.actions.read', permission: 'actions', operation: async ({ token, repository: repo }) => { const id = positive(runId, 'runId'); const expected = fullSha(expectedHeadSha, 'expectedHeadSha'); const run = await request(`${root(repo)}/actions/runs/${id}`, { token }); if (fullSha(run?.head_sha, 'run.head_sha') !== expected) fail('gh3-ci-wrong-revision', 'CI evidence belongs to another revision'); const jobs = await request(`${root(repo)}/actions/runs/${id}/jobs?per_page=${maxJobs}`, { token }); const job = (jobs?.jobs ?? []).find((item) => actionable.has(item.conclusion)); if (!job) return freeze({ repository: repo, runId: id, headSha: expected, actionable: false, reason: run.status === 'completed' ? 'no-actionable-failure' : 'run-incomplete' }); const step = (job.steps ?? []).find((item) => actionable.has(item.conclusion)) ?? null; const raw = await request(`${root(repo)}/actions/jobs/${positive(job.id, 'job.id')}/logs`, { token, text: true }); const log = String(raw ?? '').replace(/(bearer|token|secret|password)\s*[:=]\s*\S+/giu, '$1=[REDACTED]').slice(0, maxLogChars); return freeze({ repository: repo, runId: id, headSha: expected, actionable: true, job: { jobId: job.id, name: job.name }, step: step ? { number: step.number, name: step.name } : null, log, logTruncated: String(raw ?? '').length > log.length, classification: step ? 'step-failure' : 'job-failure', untrustedExternalData: true }); } }); }

  return Object.freeze({ inspectExactHead, dispatchWorkflow, rerunFailed, firstActionableFailure });
}
