import { createGitHubDevelopmentTask } from './githubDevelopmentContract.js';

function fail(code, message) { const error = new Error(message); error.name = 'GitHubDevelopmentOrchestratorError'; error.code = code; throw error; }
function required(value, field) { if (typeof value !== 'string' || value.trim() === '') fail('gh3-orchestrator-input-invalid', `${field} is required`); return value.trim(); }
function object(value, field) { if (!value || typeof value !== 'object' || Array.isArray(value)) fail('gh3-orchestrator-input-invalid', `${field} must be an object`); return value; }
function freeze(value) { if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value; for (const nested of Object.values(value)) freeze(nested); return Object.freeze(value); }
function actor(input) { return required(input.identityContext?.globalUserId, 'identityContext.globalUserId'); }
function project(input) { return required(input.scopeContext?.projectScope, 'scopeContext.projectScope'); }

export function createGitHubDevelopmentOrchestrator({ taskStore, taskExecutor = null, idFactory = () => crypto.randomUUID(), clock = () => new Date() } = {}) {
  if (!taskStore?.create || !taskStore?.get || !taskStore?.update) throw new TypeError('taskStore create/get/update is required');
  if (typeof idFactory !== 'function' || typeof clock !== 'function') throw new TypeError('invalid orchestrator dependency');

  function assertOwner(task, canonicalInput) { if (task.globalUserId !== actor(canonicalInput) || task.projectId !== project(canonicalInput)) fail('gh3-orchestrator-scope-denied', 'development task belongs to another actor or project'); }
  async function create({ canonicalInput, task: taskInput } = {}) { object(canonicalInput, 'canonicalInput'); object(taskInput, 'task'); const task = createGitHubDevelopmentTask({ ...taskInput, taskId: taskInput.taskId ?? idFactory(), globalUserId: actor(canonicalInput), projectId: project(canonicalInput), status: taskInput.status ?? 'planned' }); const existing = await taskStore.get(task.taskId); if (existing) { assertOwner(existing, canonicalInput); if (JSON.stringify(existing) !== JSON.stringify(task)) fail('gh3-orchestrator-idempotency-conflict', 'task id already has different content'); return freeze({ operation: 'create', task: existing, reused: true, mutated: false }); } await taskStore.create(task); return freeze({ operation: 'create', task, reused: false, mutated: true, observedAt: clock().toISOString() }); }
  async function status({ canonicalInput, taskId } = {}) { object(canonicalInput, 'canonicalInput'); const task = await taskStore.get(required(taskId, 'taskId')); if (!task) fail('gh3-orchestrator-task-not-found', 'development task was not found'); assertOwner(task, canonicalInput); return freeze({ operation: 'status', task, mutated: false, observedAt: clock().toISOString() }); }
  async function resume({ canonicalInput, taskId } = {}) { const current = (await status({ canonicalInput, taskId })).task; if (['completed', 'cancelled'].includes(current.status)) return freeze({ operation: 'resume', task: current, reused: true, mutated: false, terminal: true }); const running = createGitHubDevelopmentTask({ ...current, status: 'running' }); await taskStore.update(running); const execution = taskExecutor?.resume ? await taskExecutor.resume(freeze({ task: running, actorGlobalUserId: actor(canonicalInput), projectId: project(canonicalInput), traceContext: canonicalInput.traceContext })) : null; return freeze({ operation: 'resume', task: running, execution, reused: false, mutated: true }); }
  async function handle({ canonicalInput, command } = {}) { object(command, 'command'); const operation = required(command.operation, 'command.operation'); if (operation === 'create') return create({ canonicalInput, task: command.task }); if (operation === 'status') return status({ canonicalInput, taskId: command.taskId }); if (operation === 'resume') return resume({ canonicalInput, taskId: command.taskId }); fail('gh3-orchestrator-operation-unsupported', `unsupported operation: ${operation}`); }
  async function handleSemanticDecision({ canonicalInput, decisionEnvelope } = {}) { object(decisionEnvelope, 'decisionEnvelope'); if (!['github-development', 'github-development-task'].includes(decisionEnvelope.intent)) fail('gh3-orchestrator-intent-unsupported', 'semantic intent is not a GitHub development task'); const command = decisionEnvelope.selectedAction?.githubDevelopmentCommand; return handle({ canonicalInput, command: object(command, 'selectedAction.githubDevelopmentCommand') }); }
  return Object.freeze({ create, status, resume, handle, handleSemanticDecision });
}

export function createInMemoryGitHubDevelopmentTaskStore() { const tasks = new Map(); return Object.freeze({ async create(task) { if (tasks.has(task.taskId)) fail('gh3-orchestrator-task-exists', 'development task already exists'); tasks.set(task.taskId, task); }, async get(taskId) { return tasks.get(taskId) ?? null; }, async update(task) { if (!tasks.has(task.taskId)) fail('gh3-orchestrator-task-not-found', 'development task was not found'); tasks.set(task.taskId, task); } }); }
